# Generated by Django 3.2.6 on 2021-08-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_At',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
